ARG PY_DOT_VERSION
FROM python:${PY_DOT_VERSION:-3.6}

RUN apt-get update \
        && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /builds/test
RUN mkdir -p /builds/scriptworker

COPY ./requirements/ /builds/scriptworker/requirements
COPY setup.py /builds/scriptworker/
COPY setup.cfg /builds/scriptworker/
COPY scriptworker/ /builds/scriptworker/scriptworker
COPY .coveragerc /builds/scriptworker/
COPY tox.ini /builds/scriptworker/
COPY MANIFEST.in /builds/scriptworker/
COPY version.json /builds/scriptworker/

COPY secrets.json /builds/test
COPY docker/run.sh /builds/test
RUN bash -c "echo $PY_DOT_VERSION | sed -e 's/\.//' > /builds/test/pyver"

# test-specific installs
WORKDIR /builds/scriptworker/

# TODO entrypoint
ENTRYPOINT ["/bin/bash", "/builds/test/run.sh"]
CMD ["unittest"]
