FROM python:3.5

RUN apt-get update && apt-get install -y \
    git

WORKDIR /data
COPY ./requirements* /data/
COPY setup.py /data/
COPY setup.cfg /data/
COPY scriptworker/ /data/scriptworker
COPY .git /data/.git
COPY .coveragerc /data/
COPY tox.ini /data/
COPY MANIFEST.in /data/
COPY version.json /data/
COPY secrets.json /data/
RUN ls -al /data/

RUN pip3 install -r requirements-test-dev.txt
RUN python3 setup.py develop
